// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oneof.proto

package com.zheng.netty.serialize.protobuf;

public final class OneofApp {
  private OneofApp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OneofOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Oneof)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string desc = 2;</code>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 2;</code>
     */
    String getDesc();
    /**
     * <code>optional string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>optional int32 age = 3;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>optional int32 level = 4;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 4;</code>
     */
    int getLevel();

    public Oneof.TestOneofCase getTestOneofCase();

    public Oneof.TestOneof2Case getTestOneof2Case();
  }
  /**
   * Protobuf type {@code Oneof}
   */
  public  static final class Oneof extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Oneof)
      OneofOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Oneof.newBuilder() to construct.
    private Oneof(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Oneof() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Oneof(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              testOneofCase_ = 1;
              testOneof_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              testOneofCase_ = 2;
              testOneof_ = bs;
              break;
            }
            case 24: {
              testOneof2Case_ = 3;
              testOneof2_ = input.readInt32();
              break;
            }
            case 32: {
              testOneof2Case_ = 4;
              testOneof2_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OneofApp.internal_static_Oneof_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OneofApp.internal_static_Oneof_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Oneof.class, Builder.class);
    }

    private int bitField0_;
    private int testOneofCase_ = 0;
    private Object testOneof_;
    public enum TestOneofCase
        implements com.google.protobuf.Internal.EnumLite {
      NAME(1),
      DESC(2),
      TESTONEOF_NOT_SET(0);
      private final int value;
      private TestOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TestOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static TestOneofCase forNumber(int value) {
        switch (value) {
          case 1: return NAME;
          case 2: return DESC;
          case 0: return TESTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestOneofCase
    getTestOneofCase() {
      return TestOneofCase.forNumber(
          testOneofCase_);
    }

    private int testOneof2Case_ = 0;
    private Object testOneof2_;
    public enum TestOneof2Case
        implements com.google.protobuf.Internal.EnumLite {
      AGE(3),
      LEVEL(4),
      TESTONEOF2_NOT_SET(0);
      private final int value;
      private TestOneof2Case(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TestOneof2Case valueOf(int value) {
        return forNumber(value);
      }

      public static TestOneof2Case forNumber(int value) {
        switch (value) {
          case 3: return AGE;
          case 4: return LEVEL;
          case 0: return TESTONEOF2_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestOneof2Case
    getTestOneof2Case() {
      return TestOneof2Case.forNumber(
          testOneof2Case_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return testOneofCase_ == 1;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      Object ref = "";
      if (testOneofCase_ == 1) {
        ref = testOneof_;
      }
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (testOneofCase_ == 1)) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = "";
      if (testOneofCase_ == 1) {
        ref = testOneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (testOneofCase_ == 1) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 2;
    /**
     * <code>optional string desc = 2;</code>
     */
    public boolean hasDesc() {
      return testOneofCase_ == 2;
    }
    /**
     * <code>optional string desc = 2;</code>
     */
    public String getDesc() {
      Object ref = "";
      if (testOneofCase_ == 2) {
        ref = testOneof_;
      }
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (testOneofCase_ == 2)) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      Object ref = "";
      if (testOneofCase_ == 2) {
        ref = testOneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (testOneofCase_ == 2) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    /**
     * <code>optional int32 age = 3;</code>
     */
    public boolean hasAge() {
      return testOneof2Case_ == 3;
    }
    /**
     * <code>optional int32 age = 3;</code>
     */
    public int getAge() {
      if (testOneof2Case_ == 3) {
        return (Integer) testOneof2_;
      }
      return 0;
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    /**
     * <code>optional int32 level = 4;</code>
     */
    public boolean hasLevel() {
      return testOneof2Case_ == 4;
    }
    /**
     * <code>optional int32 level = 4;</code>
     */
    public int getLevel() {
      if (testOneof2Case_ == 4) {
        return (Integer) testOneof2_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testOneofCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testOneof_);
      }
      if (testOneofCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, testOneof_);
      }
      if (testOneof2Case_ == 3) {
        output.writeInt32(
            3, (int)((Integer) testOneof2_));
      }
      if (testOneof2Case_ == 4) {
        output.writeInt32(
            4, (int)((Integer) testOneof2_));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testOneofCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, testOneof_);
      }
      if (testOneofCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, testOneof_);
      }
      if (testOneof2Case_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              3, (int)((Integer) testOneof2_));
      }
      if (testOneof2Case_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              4, (int)((Integer) testOneof2_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Oneof)) {
        return super.equals(obj);
      }
      Oneof other = (Oneof) obj;

      if (!getTestOneofCase().equals(other.getTestOneofCase())) return false;
      switch (testOneofCase_) {
        case 1:
          if (!getName()
              .equals(other.getName())) return false;
          break;
        case 2:
          if (!getDesc()
              .equals(other.getDesc())) return false;
          break;
        case 0:
        default:
      }
      if (!getTestOneof2Case().equals(other.getTestOneof2Case())) return false;
      switch (testOneof2Case_) {
        case 3:
          if (getAge()
              != other.getAge()) return false;
          break;
        case 4:
          if (getLevel()
              != other.getLevel()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (testOneofCase_) {
        case 1:
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          break;
        case 2:
          hash = (37 * hash) + DESC_FIELD_NUMBER;
          hash = (53 * hash) + getDesc().hashCode();
          break;
        case 0:
        default:
      }
      switch (testOneof2Case_) {
        case 3:
          hash = (37 * hash) + AGE_FIELD_NUMBER;
          hash = (53 * hash) + getAge();
          break;
        case 4:
          hash = (37 * hash) + LEVEL_FIELD_NUMBER;
          hash = (53 * hash) + getLevel();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Oneof parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Oneof parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Oneof parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Oneof parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Oneof parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Oneof parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Oneof parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Oneof parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Oneof parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Oneof parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Oneof parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Oneof parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Oneof prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Oneof}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Oneof)
        OneofOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OneofApp.internal_static_Oneof_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OneofApp.internal_static_Oneof_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Oneof.class, Builder.class);
      }

      // Construct using com.zheng.netty.serialize.OneofApp.Oneof.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        testOneofCase_ = 0;
        testOneof_ = null;
        testOneof2Case_ = 0;
        testOneof2_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OneofApp.internal_static_Oneof_descriptor;
      }

      @Override
      public Oneof getDefaultInstanceForType() {
        return Oneof.getDefaultInstance();
      }

      @Override
      public Oneof build() {
        Oneof result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Oneof buildPartial() {
        Oneof result = new Oneof(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (testOneofCase_ == 1) {
          result.testOneof_ = testOneof_;
        }
        if (testOneofCase_ == 2) {
          result.testOneof_ = testOneof_;
        }
        if (testOneof2Case_ == 3) {
          result.testOneof2_ = testOneof2_;
        }
        if (testOneof2Case_ == 4) {
          result.testOneof2_ = testOneof2_;
        }
        result.bitField0_ = to_bitField0_;
        result.testOneofCase_ = testOneofCase_;
        result.testOneof2Case_ = testOneof2Case_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Oneof) {
          return mergeFrom((Oneof)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Oneof other) {
        if (other == Oneof.getDefaultInstance()) return this;
        switch (other.getTestOneofCase()) {
          case NAME: {
            testOneofCase_ = 1;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case DESC: {
            testOneofCase_ = 2;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case TESTONEOF_NOT_SET: {
            break;
          }
        }
        switch (other.getTestOneof2Case()) {
          case AGE: {
            setAge(other.getAge());
            break;
          }
          case LEVEL: {
            setLevel(other.getLevel());
            break;
          }
          case TESTONEOF2_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Oneof parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Oneof) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int testOneofCase_ = 0;
      private Object testOneof_;
      public TestOneofCase
          getTestOneofCase() {
        return TestOneofCase.forNumber(
            testOneofCase_);
      }

      public Builder clearTestOneof() {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
        return this;
      }

      private int testOneof2Case_ = 0;
      private Object testOneof2_;
      public TestOneof2Case
          getTestOneof2Case() {
        return TestOneof2Case.forNumber(
            testOneof2Case_);
      }

      public Builder clearTestOneof2() {
        testOneof2Case_ = 0;
        testOneof2_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return testOneofCase_ == 1;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public String getName() {
        Object ref = "";
        if (testOneofCase_ == 1) {
          ref = testOneof_;
        }
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (testOneofCase_ == 1) {
            if (bs.isValidUtf8()) {
              testOneof_ = s;
            }
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = "";
        if (testOneofCase_ == 1) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (testOneofCase_ == 1) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 1;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        if (testOneofCase_ == 1) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 1;
        testOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string desc = 2;</code>
       */
      public boolean hasDesc() {
        return testOneofCase_ == 2;
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public String getDesc() {
        Object ref = "";
        if (testOneofCase_ == 2) {
          ref = testOneof_;
        }
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (testOneofCase_ == 2) {
            if (bs.isValidUtf8()) {
              testOneof_ = s;
            }
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        Object ref = "";
        if (testOneofCase_ == 2) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (testOneofCase_ == 2) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public Builder setDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 2;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public Builder clearDesc() {
        if (testOneofCase_ == 2) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 2;
        testOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 age = 3;</code>
       */
      public boolean hasAge() {
        return testOneof2Case_ == 3;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        if (testOneof2Case_ == 3) {
          return (Integer) testOneof2_;
        }
        return 0;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        testOneof2Case_ = 3;
        testOneof2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder clearAge() {
        if (testOneof2Case_ == 3) {
          testOneof2Case_ = 0;
          testOneof2_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional int32 level = 4;</code>
       */
      public boolean hasLevel() {
        return testOneof2Case_ == 4;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public int getLevel() {
        if (testOneof2Case_ == 4) {
          return (Integer) testOneof2_;
        }
        return 0;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public Builder setLevel(int value) {
        testOneof2Case_ = 4;
        testOneof2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public Builder clearLevel() {
        if (testOneof2Case_ == 4) {
          testOneof2Case_ = 0;
          testOneof2_ = null;
          onChanged();
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Oneof)
    }

    // @@protoc_insertion_point(class_scope:Oneof)
    private static final Oneof DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Oneof();
    }

    public static Oneof getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Oneof>
        PARSER = new com.google.protobuf.AbstractParser<Oneof>() {
      @Override
      public Oneof parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Oneof(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Oneof> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Oneof> getParserForType() {
      return PARSER;
    }

    @Override
    public Oneof getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Oneof_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Oneof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Oneof.proto\"d\n\005Oneof\022\016\n\004name\030\001 \001(\tH\000\022\016" +
      "\n\004desc\030\002 \001(\tH\000\022\r\n\003age\030\003 \001(\005H\001\022\017\n\005level\030\004" +
      " \001(\005H\001B\014\n\ntest_oneofB\r\n\013test_oneof2B%\n\031c" +
      "om.zheng.netty.serializeB\010OneofApp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Oneof_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Oneof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Oneof_descriptor,
        new String[] { "Name", "Desc", "Age", "Level", "TestOneof", "TestOneof2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
